runtime: java
env: flex
 
resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10
  volumes:
  - name: ramdisk1
    volume_type: tmpfs
    size_gb: 0.5 

handlers:
  - url: /.*
    script: this field is required, but ignored